# Generated by Django 5.1.3 on 2024-12-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0002_foundid_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='device_info',
            field=models.TextField(blank=True, help_text='Device or system information that sent the message.', null=True),
        ),
    ]
