# Generated by Django 5.1.3 on 2024-12-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0003_message_device_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_contact',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
