# Generated by Django 5.1.3 on 2024-12-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0004_alter_message_sender_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundid',
            name='thumbnail',
        ),
    ]
