# Generated by Django 5.1.3 on 2024-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids', '0006_alter_foundid_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundid',
            name='image_absolute_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
